# ----------- ETAPA 1: Construir el frontend (React + Vite) ---------sss--
FROM node:18 AS frontend-builder
WORKDIR /app/frontend
COPY frontend/package*.json ./
RUN npm install
COPY frontend/ .
RUN npm run build


# ----------- ETAPA 2: Construir el backend (Node + TS + nodemon) -----------
FROM node:18 AS backend
WORKDIR /app

# Copiamos los archivos del backend
COPY backend/package*.json backend/tsconfig*.json ./ 
RUN npm install

# Copiamos el código fuente del backend
COPY backend/src ./src

# Copiamos el build del frontend a una carpeta pública del backend
COPY --from=frontend-builder /app/frontend/dist ./public

# Exponemos el puerto (ajusta si usas otro)//////////////////////
EXPOSE 3000

# Iniciamos el backend (usando ts-node + nodemon como tú pusiste)
CMD ["npx", "nodemon", "--exec", "ts-node", "src/index.ts"]
